plugins {
    id 'com.android.application'
}

android {
    namespace 'com.skipetr.planner'
    compileSdk 35

    defaultConfig {
        applicationId 'com.skipetr.planner'
        minSdk 24
        targetSdk 35
        versionCode 1
        versionName '1.0'
    }

    signingConfigs {
        release {
            storeFile file('skipetr.jks')
            storePassword 'skipetr2026'
            keyAlias 'skipetr'
            keyPassword 'skipetr2026'
        }
    }

    buildTypes {
        release {
            minifyEnabled false
            signingConfig signingConfigs.release
        }
        debug {
            signingConfig signingConfigs.release
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}
